import { Slider, SliderTrack, SliderFilledTrack, SliderThumb, Heading, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

// <Slider orientation='vertical' defaultValue={30} m={6} minH='64'>
//   <SliderTrack bg='blue.100' w={24} borderRadius={12}>
//       <SliderFilledTrack bg='blue.500'>
//       </SliderFilledTrack>
//     </SliderTrack>
//     <SliderThumb boxSize={16} borderRadius={12} minH="32" top={4} bg={"blue.100"}>
//   </SliderThumb>
// </Slider>

const Home: NextPage = () => {
  let [value, setValue] = useState(30)
  let [finalValue, setFinalValue] = useState(30)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading size="sm">Light 1</Heading>
        <Slider orientation='vertical' defaultValue={value} m={6} minH='64' onChange={(val) => setValue(val)} onChangeEnd={(val) => setFinalValue(val)}>
          <SliderTrack bg='blue.100' w={24} borderRadius={12}>
            <SliderFilledTrack bg='blue.500'>
              <SliderThumb boxSize={7} maxH={2} top={2} boxShadow="none" bg={"blue.100"}>
              </SliderThumb>
            </SliderFilledTrack>
          </SliderTrack>
        </Slider>
        <Text>{value}%</Text>
      </main>
    </div>
  )
}

export default Home
